v0.0.5
hypercore-one/znn_cli_dart pull request #2
Opened 2023-07-11 00:13 UTC by Sol-Sanctum

Implementation for feature https://github.com/hypercore-one/znn_cli_dart/issues/1

This branch adds support for the following:
- Refactored to align with the [C# znn-cli](https://github.com/KingGorrin/znn_cli_csharp)
 - Added support for HTLC, Spork, Bridge, Liquidity contracts
 - Added admin-only functionality (Bridge/Liquidity)
 - Added ability to donate to AZ and query Stats RPC
 -  Added chainId option (default, auto, manual)
 - Updated menu

Caveats
- Some [orchestrator-specific](https://github.com/hypercore-one/znn_cli_dart/blob/feature/v0.0.5/src/orchestrator.dart) functions were not implemented due to low value/increased complexity. These can potentially be omitted.
- The administrator's [Liquidity.SetTokenTuple](https://github.com/hypercore-one/znn_cli_dart/blob/feature/v0.0.5/src/liquidity.dart#L499) function is not working as expected due to an abi-encoding discrepancy

2023-07-12 11:35 UTC, KingGorrin requested changes

2023-07-12 11:35 UTC, KingGorrin commented on src/general.dart
> +      '    send toAddress amount [${green('ZNN')}/${blue('QSR')}/${magenta('ZTS')}]');
The optional message argument is missing.

2023-07-12 11:35 UTC, KingGorrin commented on src/general.dart
> +  print('    createHash "string" [hashType preimageLength]');
`createHash` only has two arguments `[hashType preimageLength]`

2023-07-12 11:35 UTC, KingGorrin commented on src/general.dart
> +  print(getZnndVersion(znnDaemon));
Why show the znnd information?

2023-07-12 11:35 UTC, KingGorrin commented on src/general.dart
> +
Negative or zero amounts are not checked.

2023-07-12 11:35 UTC, KingGorrin commented on src/general.dart
> +    block.data = AsciiEncoder().convert(args[4]);
Can UFT8 encoding be used instead?

2023-07-12 11:35 UTC, KingGorrin commented on src/general.dart
> +      print('SHA-256 Hash: $hash');
SHA2-256

2023-07-12 11:35 UTC, KingGorrin commented on src/general.dart
> +      print('SHA-3 Hash: $hash');
SHA3-256

2023-07-12 11:35 UTC, KingGorrin commented on src/htlc.dart
> +    hashLockedAddress = Address.parse(args[1]);
No checks are made to prevent empty or embedded addresses.

2023-07-12 11:35 UTC, KingGorrin commented on src/htlc.dart
> +  amount = AmountUtils.extractDecimals(num.parse(args[3]), token.decimals);
Amount as string?

2023-07-12 11:35 UTC, KingGorrin commented on src/htlc.dart
> +        return;
I think this needs to be a `break`?

2023-07-12 11:35 UTC, KingGorrin commented on src/htlc.dart
> +
No balance check is made. `if (!(await hasBalance()) return;`

2023-07-12 11:35 UTC, KingGorrin commented on src/htlc.dart
> +  Hash blockHash = Hash.parse(args[1]);
catch Hash.parse exception.

2023-07-12 11:35 UTC, KingGorrin commented on src/htlc.dart
> +      print('HashType 1 detected. Encoding preimage to SHA-256...');
SHA2-256

2023-07-12 11:35 UTC, KingGorrin commented on src/accelerator.dart
> +  if (amount == BigInt.zero) {
Check if amount is bigger than 0. `if (amount <= BigInt.zero)`

2023-07-12 11:35 UTC, KingGorrin commented on src/accelerator.dart
> +      'Donating ${AmountUtils.addDecimals(amount, token.decimals)} ${token.symbol} to Accelerator Z ...');
Accelerator-Z

2023-07-12 11:35 UTC, KingGorrin commented on src/pillar.dart
> +      Address.parse(args[2]),
Parse and check empty or embedded.

2023-07-12 11:35 UTC, KingGorrin commented on src/plasma.dart
> +  Address beneficiary = Address.parse(args[1]);
Check parse and empty or embedded address.

2023-07-12 11:35 UTC, KingGorrin commented on src/plasma.dart
> +  Hash id = Hash.parse(args[1]);
Try/catch parse

2023-07-12 11:35 UTC, KingGorrin commented on src/staking.dart
> +  Hash hash = Hash.parse(args[1]);
Try/catch hash

2023-07-12 11:35 UTC, KingGorrin commented on src/token.dart
> +  TokenStandard tokenStandard = TokenStandard.parse(args[1]);
Use GetTokenStandard()

2023-07-12 11:35 UTC, KingGorrin commented on src/token.dart
> +  Token token = (await znnClient.embedded.token.getByZts(tokenStandard))!;
Check if token exist

2023-07-12 11:35 UTC, KingGorrin commented on src/token.dart
> +  Address ownerAddress = Address.parse(args[1]);
Check parse address.

2023-07-12 11:35 UTC, KingGorrin commented on src/token.dart
> +  TokenStandard tokenStandard = TokenStandard.parse(args[1]);
Use GetTokenStandard()

2023-07-12 11:35 UTC, KingGorrin commented on src/token.dart
> +  TokenStandard tokenStandard = TokenStandard.parse(args[1]);
Use GetTokenStandard()

2023-07-12 11:35 UTC, KingGorrin commented on src/token.dart
> +  Address newOwnerAddress = Address.parse(args[2]);
Check parse address

2023-07-12 11:35 UTC, KingGorrin commented on src/token.dart
> +  TokenStandard tokenStandard = TokenStandard.parse(args[1]);
Use GetTokenStandard()

2023-07-12 11:35 UTC, KingGorrin commented on src/token.dart
> +  var token = (await znnClient.embedded.token.getByZts(tokenStandard))!;
Check if token exists

2023-07-12 11:35 UTC, KingGorrin commented on src/token.dart
> +  var token = (await znnClient.embedded.token.getByZts(tokenStandard))!;
Check if token exists

2023-07-12 11:35 UTC, KingGorrin commented on src/liquidity.dart
> +  Address address = Address.parse(args[1]);
Try/Catch parse address

2023-07-12 11:35 UTC, KingGorrin commented on src/liquidity.dart
> +  Address address = Address.parse(args[1]);
Try/catch parse address

2023-07-12 11:35 UTC, KingGorrin commented on src/liquidity.dart
> +  Address address = Address.parse(args[1]);
Try/catch parse address

2023-07-12 11:35 UTC, KingGorrin commented on src/liquidity.dart
> +  TokenStandard tokenStandard = TokenStandard.parse(args[3]);
Use GetTokenStandard

2023-07-12 11:35 UTC, KingGorrin commented on src/liquidity.dart
> +  Hash id = Hash.parse(args[1]);
Try/catch parse hash

2023-07-12 11:35 UTC, KingGorrin commented on src/liquidity.dart
> +  Address newAdmin = Address.parse(args[1]);
Try/catch parse address and check new admin must be an user address.

2023-07-12 11:35 UTC, KingGorrin commented on src/liquidity.dart
> +  Address newAdmin = Address.parse(args[1]);
Try/catch parse address and check not empty or embedded

2023-07-12 11:35 UTC, KingGorrin commented on src/liquidity.dart
> +
Nomination works with time challenges, see  C# impl. for details.

2023-07-12 11:35 UTC, KingGorrin commented on src/liquidity.dart
> +      if (guardian != emptyAddress) {
Check not empty or embedded and all are distinct

2023-07-12 11:35 UTC, KingGorrin commented on src/liquidity.dart
> +          TokenStandard.parse('zts17d6yr02kh0r9qr566p7tg6'));
Why is the token standard hardcoded?

2023-07-12 11:35 UTC, KingGorrin commented on src/plasma.dart
> +  }
Assert pageIndex/pageSize constraints

2023-07-12 11:35 UTC, KingGorrin commented on src/spork.dart
> +  }
Assert pageIndex/pageSize constraints

2023-07-12 11:35 UTC, KingGorrin commented on src/staking.dart
> +  }
Assert pageIdex/pageSize constraints

2023-07-12 11:35 UTC, KingGorrin commented on src/token.dart
> +  }
Assert pageIndex/pageSize constraints

2023-07-12 11:35 UTC, KingGorrin commented on src/token.dart
> +  Address mintAddress = Address.parse(args[3]);
Try/catch parse address

2023-07-12 11:35 UTC, KingGorrin commented on src/bridge.dart
> +  if (amount == BigInt.zero) {
amount must be greater than 0

2023-07-12 11:35 UTC, KingGorrin commented on src/bridge.dart
> +  Hash id = Hash.parse(args[1]);
Try/catch parse hash

2023-07-12 11:35 UTC, KingGorrin commented on src/bridge.dart
> +  Hash transactionHash = Hash.parse(args[1]);
Try/catch parse hash

2023-07-12 11:35 UTC, KingGorrin commented on src/bridge.dart
> +  print('   Amount: ${AmountUtils.addDecimals(request.amount, decimals)}');
Token symbol is not displayed

2023-07-12 11:35 UTC, KingGorrin commented on src/bridge.dart
> +  print('   Amount: ${AmountUtils.addDecimals(request.amount, decimals)}');
Token symbol is not displayed

2023-07-12 11:35 UTC, KingGorrin commented on src/bridge.dart
> +  Address newAdmin = Address.parse(args[1]);
Check parse and assert not empty or embedded address

2023-07-12 11:35 UTC, KingGorrin commented on src/bridge.dart
> +  AccountBlockTemplate halt = znnClient.embedded.bridge.halt('');
Use signature value '1' to circumvent the empty string unpack issue.

2023-07-12 11:35 UTC, KingGorrin commented on src/bridge.dart
> +  print('Removing token pair ...');
Invalid print statement.

2023-07-12 11:35 UTC, KingGorrin commented on src/bridge.dart
> +
Nomination works with time challenges, see C# impl. for details.

2023-07-12 11:35 UTC, KingGorrin commented on src/bridge.dart
> +  Address newAdmin = Address.parse(args[1]);
Check parse and assert not empty or embedded address.

2023-07-12 11:35 UTC, KingGorrin commented on src/bridge.dart
> +}
`bridge.admin.setRedeemDelay` is missing?

2023-07-12 12:01 UTC, KingGorrin requested changes
@Sol-Sanctum I've reviewed the changes and made lots of inline comments. Most are about assertions and inconsistencies between other methods. I'm not sure about all the comments, so if you can give your rationale I'd appreciate it. I've already included your changes in the `bigint` branch of the C# CLI. I await your answers in order to finalize the implementation.

2023-07-12 23:01 UTC, Sol-Sanctum commented on src/bridge.dart
> +}
Omitted on purpose due to incomplete implementation in go-zenon.

1. [Definition statement](https://github.com/zenon-network/go-zenon/blob/master/vm/embedded/definition/bridge.go#L101)
2. [Missing abi](https://github.com/zenon-network/go-zenon/blob/master/vm/embedded/embedded.go#L59)
3. [Missing SetRedeemDelayMethod](https://github.com/zenon-network/go-zenon/blob/master/vm/embedded/implementation/bridge.go)

2023-07-13 06:31 UTC, KingGorrin commented on src/bridge.dart
> +}
I should have checked go-zenon. Thanks for the insight.

2023-07-14 01:45 UTC, Sol-Sanctum commented on src/general.dart
> +  print(getZnndVersion(znnDaemon));
Agree, it wasn't really valuable information.

2023-07-14 07:11 UTC, KingGorrin commented on src/general.dart
> +  print(getZnndVersion(znnDaemon));
The `process.info` command shows all the info you need.

Also, we need to do something about the versioning schema. I would like to align my versions, but I'm using semantic versioning.

2023-07-15 22:04 UTC, Sol-Sanctum commented
Thank you for reviewing my work and providing detailed feedback. 
I believe I've addressed most of your comments in this commit: https://github.com/hypercore-one/znn_cli_dart/pull/2/commits/77a3b7fae06f1e713d4c0027ed169d70c4951908

A few stood out, though:
1. [Semantic versioning](https://github.com/hypercore-one/znn_cli_dart/pull/2#discussion_r1263384647)
2. I don't understand [this one](https://github.com/hypercore-one/znn_cli_dart/pull/2#discussion_r1259528074)?
3. I don't think [this](https://github.com/hypercore-one/znn_cli_dart/pull/2#discussion_r1260966259) needs a populated string but we can fix it in a future commit. Will have to check out [this issue.](https://github.com/hypercore-one/znn_sdk_dart/issues/1)

PS: I refactored a bit more. I'm much happier with this structure. Sorry in advance 😬

2023-07-18 08:18 UTC, KingGorrin approved these changes

2023-07-18 08:18 UTC, KingGorrin commented on lib/accelerator.dart
>    print('  ${white('Accelerator Z')}');
Accelerator-Z 🤣

2023-07-18 08:24 UTC, KingGorrin commented on src/htlc.dart
> +  amount = AmountUtils.extractDecimals(num.parse(args[3]), token.decimals);
Forget this one.

2023-07-18 08:26 UTC, KingGorrin commented
Very nice work in total!

2024-03-10 15:18 UTC, closed without merging